language: java
jdk: openjdk18

# Need to ensure full depth clone for SonarCloud blame
git:
  depth: false

addons:
  sonarcloud:
    projectKey: JCL
    organization: "scodynelson"

install:
  # Display Gradle, JVM, and other versions
  - ./gradlew --version

script:
# Run Build
  - ./gradlew build
# Run SonarQube Report
  - ./gradlew sonarqube

after_success:
  - bash <(curl -s https://codecov.io/bash)