language: java
jdk: openjdk21

# Need to ensure full depth clone for SonarCloud blame
git:
  depth: false

addons:
  sonarcloud:
    organization: "scodynelson"
    token:
      secure: N/acBLsyuCCcmippD3fdaZgE4e9p3ehk31oPfgI4UnyrPLQQJZ0ud9BfsfpXTCvcX2Y274m1kA+TGkfNzETy1AriCwCn5DTwCOdEaoVG85OLAslGTgXNpftyjfOlekJ9XH3FHwRmelHRXLBLcIVlAnXJUHQpktcniOWlkpuLhj7hCP11kWqE6fxEqmndqdc47OYqq7e1BdWWUHnhcUz7BB9rtfBnL7I3/rx6TtAIDBiZyOW7l/Xs9ZZYUhB4cy/DIWwPfJ3BLCHzJKR89hYg2Ilb4fRvYaQ8II8gFAI5zQAsy6zaU5mgICVzK878a8U55EHgDDeKRIC54++djDAahfcr0NflnOWXzHrWvfJbwa0y9cOmyOvBzCC/eE2hXD81YY0GkrW9pdycaL/euAkcEo7tBFlkRWIVRSiQMbCOBQ94QWnfH441n0Q3z7wyzJSD4ZZfTR6olK7GPvkEaitE8U92PPtyU/xTAZcT1pZZf3is4S6mXQ7WuH4/4Fb0q4YaccZgw9RLohT4sZSB8WrQxhgnwAtPu+MnSzHaBPskzg5eFTEFW1wuUNk+iEs/Fif+8piyCsH4Ov+clTTooka88g9heNxerA9bESCtQKbJvxowMUibc1EqI2lk1kSit5XOR2u8/fa1a9Pt4xCu/kxFhwTSf2B70QhkN/CG3cWmkNM=

install:
  # Display Gradle, JVM, and other versions
  - ./gradlew --version

script:
# Run Build
  - ./gradlew build
# Run SonarQube Report
  - ./gradlew assemble sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)