# Language
language: java
# JDK Version
jdk: oraclejdk8
# Gradle Script
script: ./gradlew check
# Gradle Caching
#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
##cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/