language: java
jdk: openjdk17

before_script:
  - chmod +x gradlew

script:
# Display Gradle, JVM, and other versions
  - ./gradlew --version
# Run all checks
  - ./gradlew check
# Verify Code Generation
  - ./gradlew assemble
# Run code coverage report
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)