language: java
jdk: openjdk18

before_script:
  - chmod +x gradlew

script:
# Display Gradle, JVM, and other versions
  - ./gradlew --version
# Run Build and generate JaCoCo Report
  - ./gradlew build jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)