language: java
jdk: openjdk18

addons:
  sonarcloud:
    projectKey: JCL
    organization: "scodynelson"

before_script:
  - chmod +x gradlew

script:
# Display Gradle, JVM, and other versions
  - ./gradlew --version
# Run Build
  - ./gradlew build
# Run Tests, Generate JaCoCo Test Report, Upload Report to SonarQube
  - ./gradlew test jacocoTestReport sonarqube --info --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)