language: java
jdk: openjdk18

# Need to ensure full depth clone for SonarCloud blame
git:
  depth: false

addons:
  sonarcloud:
    projectKey: JCL
    organization: "scodynelson"

install:
  # Display Gradle, JVM, and other versions
  - ./gradlew --version

script:
# Run Build
  - ./gradlew build --warning-mode all
# Run Tests, Generate JaCoCo Test Report, Upload Report to SonarQube
  - ./gradlew test jacocoTestReport sonarqube --info --stacktrace --warning-mode all

after_success:
  - bash <(curl -s https://codecov.io/bash)