package jcl.structs.symbols;

public enum Constant {

	CALL_ARGUMENTS_LIMIT,
	LAMBDA_LIST_KEYWORDS,
	LAMBDA_PARAMETERS_LIMIT,
	NIL,
	T,
	MULTIPLE_VALUES_LIMIT,
	PI,

	BOOLE_1,
	BOOLE_2,
	BOOLE_AND,
	BOOLE_ANDC1,
	BOOLE_ANDC2,
	BOOLE_C1,
	BOOLE_C2,
	BOOLE_CLR,
	BOOLE_EQV,
	BOOLE_IOR,
	BOOLE_NAND,
	BOOLE_NOR,
	BOOLE_ORC1,
	BOOLE_ORC2,
	BOOLE_SET,
	BOOLE_XOR,

	MOST_POSITIVE_FIXNUM,
	MOST_NEGATIVE_FIXNUM,

	MOST_POSITIVE_SHORT_FLOAT,
	LEAST_POSITIVE_SHORT_FLOAT,
	LEAST_POSITIVE_NORMALIZED_SHORT_FLOAT,
	MOST_NEGATIVE_SHORT_FLOAT,
	LEAST_NEGATIVE_SHORT_FLOAT,
	LEAST_NEGATIVE_NORMALIZED_SHORT_FLOAT,
	SHORT_FLOAT_EPSILON,
	SHORT_FLOAT_NEGATIVE_EPSILON,

	MOST_POSITIVE_SINGLE_FLOAT,
	LEAST_POSITIVE_SINGLE_FLOAT,
	LEAST_POSITIVE_NORMALIZED_SINGLE_FLOAT,
	MOST_NEGATIVE_SINGLE_FLOAT,
	LEAST_NEGATIVE_SINGLE_FLOAT,
	LEAST_NEGATIVE_NORMALIZED_SINGLE_FLOAT,
	SINGLE_FLOAT_EPSILON,
	SINGLE_FLOAT_NEGATIVE_EPSILON,

	MOST_POSITIVE_DOUBLE_FLOAT,
	LEAST_POSITIVE_DOUBLE_FLOAT,
	LEAST_POSITIVE_NORMALIZED_DOUBLE_FLOAT,
	MOST_NEGATIVE_DOUBLE_FLOAT,
	LEAST_NEGATIVE_DOUBLE_FLOAT,
	LEAST_NEGATIVE_NORMALIZED_DOUBLE_FLOAT,
	DOUBLE_FLOAT_EPSILON,
	DOUBLE_FLOAT_NEGATIVE_EPSILON,

	MOST_POSITIVE_LONG_FLOAT,
	LEAST_POSITIVE_LONG_FLOAT,
	LEAST_POSITIVE_NORMALIZED_LONG_FLOAT,
	MOST_NEGATIVE_LONG_FLOAT,
	LEAST_NEGATIVE_LONG_FLOAT,
	LEAST_NEGATIVE_NORMALIZED_LONG_FLOAT,
	LONG_FLOAT_EPSILON,
	LONG_FLOAT_NEGATIVE_EPSILON,

	CHAR_CODE_LIMIT,

	ARRAY_DIMENSION_LIMIT,
	ARRAY_RANK_LIMIT,
	ARRAY_TOTAL_SIZE_LIMIT,

	INTERNAL_TIME_UNITS_PER_SECOND
}
