package jcl.reader.state;

public enum States {

	READ(1),
	ILLEGAL_CHARACTER(2),
	WHITESPACE(3),
	MACRO_CHARACTER(4),
	SINGLE_ESCAPE(5),
	MULTIPLE_ESCAPE(6),
	CONSTITUENT(7),
	EVEN_MULTI_ESCAPE(8),
	ODD_MULTI_ESCAPE(9),
	TOKEN_ACCUMULATED(10),
	NUMBER_TOKEN_ACCUMULATED(10.1),
	INTEGER_TOKEN_ACCUMULATED(10.11),
	FLOAT_TOKEN_ACCUMULATED(10.12),
	RATIONAL_TOKEN_ACCUMULATED(10.13),
	RATIONAL_FLOAT_TOKEN_ACCUMULATED(10.14),
	SYMBOL_TOKEN_ACCUMULATED(10.2);

	private final double step;

	States(final double step) {
		this.step = step;
	}
}
