name: Build JCL

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Display Gradle, JVM, and other versions
        run: ./gradlew --version
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Upload CodeCov
        uses: codecov/codecov-action@v3
